### ISSUE TITLE
`genAnnotatedElements.<fn>` fails with Null check operator used on a null value.

### ISSUE THREAD

**Issue by SunlightBro** [kevmoo/source_gen_test#42]
With version 1.3.0 of source_gen [commit](https://github.com/dart-lang/source_gen/commit/c53727e46df4b4b7e32519568af87999f07a3288)

expectation_element.dart [genAnnotatedElements()](https://github.com/kevmoo/source_gen_test/blob/1576ff7eb9271dab6a6c4da474a7c765f18996bb/lib/src/expectation_element.dart#L13)
can fail with Null check operator used on a null value.

If the LibraryReader has elements of type `LibraryImportElementImpl` that have name = null.

For reference here a test from freezed [source_gen_test.dart](https://github.com/rrousselGit/freezed/blob/master/packages/freezed/test/source_gen_test.dart)

```log
Failed to load "/Users/sunbro/dev/freezed/packages/freezed/test/source_gen_test.dart": Null check operator used on a null value

package:source_gen_test/src/expectation_element.dart 13:28     genAnnotatedElements.<fn>
dart:collection                                                ListMixin.sort
package:source_gen_test/src/expectation_element.dart 13:7      genAnnotatedElements
package:source_gen_test/src/test_annotated_classes.dart 104:7  getAnnotatedClasses
package:source_gen_test/src/test_annotated_classes.dart 33:21  testAnnotatedElements
test/source_gen_test.dart 13:3                                 main
```

One solution/workaround could be to write:
```diff
-  final allElements = libraryReader.allElements.toList(growable: false)
+  final allElements = libraryReader.allElements.takeWhile((e) => e.name != null).toList(growable: false)
     ..sort((a, b) => a.name!.compareTo(b.name!));
```

But please let me know if you have a better idea to fix this and if you want a PR.

**Comment by kevmoo** [comment]
looking now!
