### ISSUE TITLE
How do I split test case to different files?

### ISSUE THREAD

**Issue by trevorwang** [kevmoo/source_gen_test#9]
https://github.com/trevorwang/retrofit.dart/commit/ac2cf5cabd2d21f367137c7c860f9bbe810ed2be

I have written some test cases. How dow I split the two cases to 2 files?
I tried add another  test_src file in the src folder. But it seemed only the file configured in main function can be executed.

**Comment by devkabiir** [comment]
There are two ways.

1. Create a library `generator_test_src.dart` with content
```dart
library geenrator_test;
part 'test_1';
part 'test_2';
```
and separate your test cases in those files. After that you will have multiple files for test cases and you only have to include one file in the `main` function
```dart
  final reader = await initializeLibraryReaderForDirectory(
      'test/src', 'generator_test_src.dart');
```

2. Create different readers for each test case
```dart
  final testHttpGet = await initializeLibraryReaderForDirectory(
      'test/src', 'generator_http_get_test.dart');
```
```dart
  final testHttpPost = await initializeLibraryReaderForDirectory(
      'test/src', 'generator_http_post_test.dart');
```

And then 

```dart
testAnnotatedElements<http.RestApi>(testHttpGet , RetrofitGenerator());
testAnnotatedElements<http.RestApi>(testHttpPost , RetrofitGenerator());
```

**Comment by trevorwang** [comment]
Thanks. @devkabiir 

But I am looking forward to the same way as a normal test runs.

I just put all test src in one folder and the lib handle all other things.

**Comment by devkabiir** [comment]
The function `testAnnotatedElements` runs the `test()` function internally. So the only way to write tests in different files and *automatically* run them is by using the first option->

>     1. Create a library `generator_test_src.dart` with content
Then you can have test cases in files `test_1.dart` and `test_2.dart` as follows
```dart
part of geenrator_test;

/// Your test here
@ShouldGenerate('something')
@YourAnnotation
class test_case_1{}
```

**Comment by trevorwang** [comment]
Yeah.  But you cannot use the same class name even you split into different files.

**Comment by devkabiir** [comment]
> Yeah. But you cannot use the same class name even you split into different files.

You can use the same class name if you use option 2. from my original post
```dart
testAnnotatedElements<http.RestApi>(testHttpPost , RetrofitGenerator());
testAnnotatedElements<http.RestApi>(testHttpGet , RetrofitGenerator());
```

Also the class name is used as the test name so it's not a good idea to use the same class name for multiple test cases. Because the test names are the names of the actual elements you should use different names. 
example output:
```
> pub run test
00:00 +0: logs_when_route_hierarchy_is_wrong /// This is the name of the class
00:00 +1: throws_for_annotated_field /// This is the name of the field
00:00 +2: throws_for_annotated_function /// This is the name of the function
00:00 +3: throws_when_route_name_is_null
00:00 +4: (tearDownAll)
00:00 +4: All tests passed!
```


But if you want to test the same class for two cases you can annotate it twice.
```dart
@ShouldGenerate('first output')
@ShouldGenerate('second output')
class MyClass {}
```

**Comment by trevorwang** [comment]
yeah. it's the best choice so far.
